const WebSocketType={
    GAME_START: 'GAME_START',
    PLAYER_ADD: 'PLAYER_ADD',
    PLAYER_REMOVE: 'PLAYER_REMOVE',
    ROUND_UPDATE: 'ROUND_UPDATE',
    ANSWER_UPDATE: 'ANSWER_UPDATE',
    GAME_END: 'GAME_END',
};
export default WebSocketType;