const WebSocketType={
    GAME_INIT: 'GAME_INIT',
    PLAYER_ADD: 'PLAYER_ADD',
    PLAYRE_REMOVE: 'PLAYRE_REMOVE',
    ROUND_UPDATE: 'ROUND_UPDATE',
    ANSWER_UPDATE: 'ANSWER_UPDATE',
    GAME_END: 'GAME_END',
};
export default WebSocketType;